### Add John

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email":"John_the_First@Gmail.com",

  "password": "Hello!123"

}

### Add Willy

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "Willy_the_Second@gmail.com",
  "password": "Willy_the_Second!12"

}

### Get All Users

GET localhost:8080/api/users?page=0&orderBy=email

### Get Confirmed user
GET localhost:8080/api/users?orderBy=email&desc=true&page=0&filterBy=state&filterValue=CONFIRMED

### Get user 1

GET http://localhost:8080/api/users/1

### Get user 2

GET http://localhost:8080/api/users/2

### Delete user

DELETE localhost:8080/api/users/

### Update User 1

PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "newRole" : "MANAGER",
  "newState" : "CONFIRMED"
}

### Update user 2

PUT http://localhost:8080/api/users/2
Content-Type: application/json

{
  "newRole" : "MANAGER",
  "newState" : "CONFIRMED"
}

### Get user 1

GET http://localhost:8080/api/users/1
