### Add John

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "loginName": "John the First"

}

### Add Willy

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "loginName": "Willy the Second"

}

### Get All Users

GET localhost:8080/api/users


### Get user 1

GET http://localhost:8080/api/users/1

### Get user 2

GET http://localhost:8080/api/users/2